version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
           - raimunDb
           - rabbitmq

  rabbitmq:
     image: rabbitmq:3-management-alpine

        
  raimunDb:
     image: mcr.microsoft.com/mssql/server:latest
     environment:
            SA_PASSWORD: "123456"
            ACCEPT_EULA: "Y"
  
